/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    uint32_t *pClkctrlreg = (uint32_t*)0x40023830;
    uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
    uint32_t *pPortDOutReg = (uint32_t*)0x40020C14;

    //1. enable the clock for GPOID peripheral in the AHB1ENR
    /*
     * it is same usage for below code.
   	uint32_t temp = *pClkCtrlReg;  //read operation
    temp = temp | 0x08;	//modify
    *pClkctrlreg = temp; //write back
    */
    *pClkctrlreg |= (1 << 3); // shorcut for this *pClkctrlreg = *pClkctrlreg | 0x08;

    //2. configure the mode of the IO pin as output.
    //a. clear the 24th and 25th bit positions (CLEAR)
    *pPortDModeReg &= ~(3 << 26);
    //b. make the 24th bit position as 1 (SET)
    *pPortDModeReg |= (1 << 26);

    //3. SET 12th bit of the output data register to make ı/o pin-12 HIGH
    *pPortDOutReg |= (1 << 13);

	while(1);
}
