/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
//Important part which I forget. Out main.h is not a common library because of that we need to define it like "main.c".

/*
 * uint32_t *pClkctrlreg = (uint32_t*)0x40023830;
 * uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
 * uint32_t *pPortDOutReg = (uint32_t*)0x40020C14;
*/

int main(void)
{
	RCC_AHB1ENR_t volatile *const pClkCtrl = (RCC_AHB1ENR_t *)0x40023830;
	pClkCtrl->gpioDen = 1;

	GPIOx_MODER_t volatile *const pPortDModeReg = (GPIOx_MODER_t *)0x40020C00;
	pPortDModeReg->mode13 = 1;

	GPIOx_ODR_t volatile *const pPortDOutReg = (GPIOx_ODR_t *)0x40020C14;
	pPortDOutReg->odr13 = 1;
}
