/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
		uint32_t *pClkctrlreg = (uint32_t*)0x40023830;
	    uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	    uint32_t *pPortDOutReg = (uint32_t*)0x40020C14;

	    *pClkctrlreg |= (1 << 3);
	    *pPortDModeReg &= ~(3 << 26);
	    *pPortDModeReg |= (1 << 26);

	    while(1){

	    *pPortDOutReg |= (1 << 13);

	    for(uint32_t i = 0; i<100000; i++);
	    //turn off the LED
	    *pPortDOutReg &= ~(1 << 13);
	    //introduce small human obserable delay
	    for(uint32_t i = 0; i<1000000; i++);
	    }

}
