/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	while(1)
	{
		uint32_t *pClkControlReg = (uint32_t*)0x40023830;
		uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
		uint32_t *pPortDOutReg = (uint32_t*)0x40020C14;

		*pClkControlReg |= (1 << 3);
		*pPortDModeReg &= ~(3 << 26);
		*pPortDModeReg |= (1 << 26);
		*pPortDOutReg |= (1 << 13);
	}
}
