/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>



void button_init(void);


uint32_t volatile *pClkCtrlReg = (uint32_t*)(0x40023800 + 0x30);
uint32_t volatile *pClkCtrlRegApb2 = (uint32_t*)(0x40023800 + 0x44);
uint32_t volatile *pGPIOAModeReg = (uint32_t*)(0x40020000 + 0x00);
uint32_t volatile *pEXTIPendReg = (uint32_t*)(0x40013C00 + 0x14);
uint32_t volatile *pEXTIMaskReg = (uint32_t*)(0x40013C00 + 0x00);
uint32_t volatile *pEXTIEdgeCtrlReg = (uint32_t*)(0x40013C00 + 0x08);
uint32_t volatile *pNVICIRQEnReg = (uint32_t*) 0xE000E100;
// I still couldn't get to find NVIC address. I found this value from chatGpt.


int main(void)
{
	button_init();

	while(1){
		//Disable interrupt
		*pEXTIMaskReg &= ~( 1 << 0);

		if(g_button_pressed){
		//Some delay until button debouncing gets over
		for(uint32_t volatile i=0;i<500000/2;i++);
		g_button_press_count++;
		printf("Button is pressed : %lu\n",g_button_press_count);
		g_button_pressed = 0;
		}

		//Enable interrupt
		*pEXTIMaskReg |= ( 1 << 0);

	}
}
